### ISSUE TITLE
Where is tracing-etw?

### ISSUE THREAD

**Issue by oherrala** [microsoft/rust_win_etw#23]
The repository's [README.md](https://github.com/microsoft/rust_win_etw/blob/e95aaba3351e27c6f5c9605f2e62ae97942cad55/README.md?plain=1#L15) mentions `tracing-etw` and points to non-existent repository in https://github.com/microsoft/tracing-etw.

Is there still `tracing-etw` somewhere or other means to use [`tracing`](https://tracing.rs/) framework with ETW?

**Comment by cijothomas** [comment]
It is here : https://github.com/microsoft/rust_win_etw/tree/main/win_etw_tracing

https://github.com/microsoft/rust_win_etw/pull/26/files fixed the main readme as well.
