### ISSUE TITLE
UUID feature in 0.1.10 requires "std" feature to build.

### ISSUE THREAD

**Issue by kharpMSFT** [microsoft/rust_win_etw#37]
Using v0.1.10 of the crate I get a build error in guid.rs when using only the "uuid" feature.
`win_etw_provider = { version = "0.1.10", features = ["uuid"] }`

Using "uuid" & "std" avoids the break, 
`win_etw_provider = { version = "0.1.10", features = ["std", "uuid"] }`

but "std" was not required in v0.1.9
`win_etw_provider = { version = "=0.1.9", features = ["uuid"] }`

@NateD-MSFT, Quick looks finds #35 as a possible source for this.

**Simple repro**
```
cargo new provider_test
cd provider_test
cargo add win_etw_provider --features=uuid
cargo build

   Compiling win_etw_provider v0.1.10
error[E0599]: no method named `to_owned` found for reference `&[u8; 8]` in the current scope
   --> <snip...>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\win_etw_provider-0.1.10\src\guid.rs:108:29
    |
108 |             data4: fields.3.to_owned(),
    |                             ^^^^^^^^ method not found in `&[u8; 8]`
    |
    = help: items from traits can only be used if the trait is in scope
help: trait `ToOwned` which provides `to_owned` is implemented but not in scope; perhaps you want to import it
    |
1   + use crate::alloc::borrow::ToOwned;
    |
```

**Comment by NateD-MSFT** [comment]
Good catch, I forgot to check the UUID feature when testing.  Opened #38 to fix; @sivadeilra please review and approve when you have a moment.
